title: "Hormone Heroics"
description: "Balance, vitality, and wellness through smarter hormones"
baseurl: ""
url: "https://hormoneheroics.github.io"

author:
  name: "Hormone Heroics Team"
  email: contact@hormoneheroics.com

social:
  email: contact@hormoneheroics.com
  facebook: https://www.facebook.com/hormoneheroics
  instagram: https://www.instagram.com/hormoneheroics

markdown: kramdown

remote_theme: pages-themes/minimal@v0.2.0


plugins:
  - jekyll-feed
  - jekyll-seo-tag
